import LoginForm from "@/components/login/LoginForm";
import { redirect, RedirectType } from "next/navigation";
import { getSession } from "../api/auth/[...nextauth]/route";

export const metadata = {
  title: "Connexion - TRB Eshop",
  description: "Generated by create next app",
};

export default async function Login() {
  const session = await getSession();

  return !session ? (
    <main className="flex h-screen w-screen items-center justify-center">
      <LoginForm />
      {/* {JSON.stringify(session.user)} */}
    </main>
  ) : session.user?.email === process.env.GOOGLE_ADMIN_EMAIL ? (
    redirect("/dashboard", RedirectType.replace)
  ) : (
    redirect("/", RedirectType.replace)
  );
}
