import { uniqueId } from "../src/lib/utils";
import { Prisma } from "@prisma/client";

export const wilayaData: Prisma.WilayaUncheckedCreateInput[] = [
  {
    name: "Adrar",
    arName: "أدرار",
    code: 1,
  },
  {
    // id: 2,
    name: "Chlef",
    arName: "الشلف",
    code: 2,
  },
  {
    // id: 3,
    name: "Laghouat",
    arName: "الأغواط",
    code: 3,
  },
  {
    // id: 4,
    name: "Oum El Bouaghi",
    arName: "أم البواقي",
    code: 4,
  },
  {
    // id: 5,
    name: "Batna",
    arName: "باتنة",
    code: 5,
  },
  {
    // id: 6,
    name: "Béjaïa",
    arName: "بجاية",
    code: 6,
  },
  {
    // id: 7,
    name: "Biskra",
    arName: "بسكرة",
    code: 7,
  },
  {
    // id: 8,
    name: "Béchar",
    arName: "بشار",
    code: 8,
  },
  {
    // id: 9,
    name: "Blida",
    arName: "البليدة",
    code: 9,
  },
  {
    // id: 10,
    name: "Bouïra",
    arName: "البويرة",
    code: 10,
  },
  {
    // id: 11,
    name: "Tamanrasset",
    arName: "تمنراست",
    code: 11,
  },
  {
    // id: 12,
    name: "Tébessa",
    arName: "تبسة",
    code: 12,
  },
  {
    // id: 13,
    name: "Tlemcen",
    arName: "تلمسان",
    code: 13,
  },
  {
    // id: 14,
    name: "Tiaret",
    arName: "تيارت",
    code: 14,
  },
  {
    // id: 15,
    name: "Tizi Ouzou",
    arName: "تيزي وزو",
    code: 15,
  },
  {
    // id: 16,
    name: "Alger",
    arName: "الجزائر",
    code: 16,
  },
  {
    // id: 17,
    name: "Djelfa",
    arName: "الجلفة",
    code: 17,
  },
  {
    // id: 18,
    name: "Jijel",
    arName: "جيجل",
    code: 18,
  },
  {
    // id: 19,
    name: "Sétif",
    arName: "سطيف",
    code: 19,
  },
  {
    // id: 20,
    name: "Saïda",
    arName: "سعيدة",
    code: 20,
  },
  {
    // id: 21,
    name: "Skikda",
    arName: "سكيكدة",
    code: 21,
  },
  {
    // id: 22,
    name: "Sidi Bel Abbès",
    arName: "سيدي بلعباس",
    code: 22,
  },
  {
    // id: 23,
    name: "Annaba",
    arName: "عنابة",
    code: 23,
  },
  {
    // id: 24,
    name: "Guelma",
    arName: "قالمة",
    code: 24,
  },
  {
    // id: 25,
    name: "Constantine",
    arName: "قسنطينة",
    code: 25,
  },
  {
    // id: 26,
    name: "Médéa",
    arName: "المدية",
    code: 26,
  },
  {
    // id: 27,
    name: "Mostaganem",
    arName: "مستغانم",
    code: 27,
  },
  {
    // id: 28,
    name: "M'Sila",
    arName: "المسيلة",
    code: 28,
  },
  {
    // id: 29,
    name: "Mascara",
    arName: "معسكر",
    code: 29,
  },
  {
    // id: 30,
    name: "Ouargla",
    arName: "ورقلة",
    code: 30,
  },
  {
    // id: 31,
    name: "Oran",
    arName: "وهران",
    code: 31,
  },
  {
    // id: 32,
    name: "El Bayadh",
    arName: "البيض",
    code: 32,
  },
  {
    // id: 33,
    name: "Illizi",
    arName: "اليزي",
    code: 33,
  },
  {
    // id: 34,
    name: "Bordj Bou Arréridj",
    arName: "برج بوعريريج",
    code: 34,
  },
  {
    // id: 35,
    name: "Boumerdès",
    arName: "بومرداس",
    code: 35,
  },
  {
    // id: 36,
    name: "El Tarf",
    arName: "الطارف",
    code: 36,
  },
  {
    // id: 37,
    name: "Tindouf",
    arName: "تندوف",
    code: 37,
  },
  {
    // id: 38,
    name: "Tissemsilt",
    arName: "تسمسيلت",
    code: 38,
  },
  {
    // id: 39,
    name: "El Oued",
    arName: "الوادي",
    code: 39,
  },
  {
    // id: 40,
    name: "Khenchela",
    arName: "خنشلة",
    code: 40,
  },
  {
    // id: 40,
    name: "Souk Ahras",
    arName: "سوق أهراس",
    code: 41,
  },
  {
    // id: 42,
    name: "Tipaza",
    arName: "تيبازة",
    code: 42,
  },
  {
    // id: 43,
    name: "Mila",
    arName: "ميلة",
    code: 43,
  },
  {
    // id: 44,
    name: "Aïn Defla",
    arName: "عين الدفلى",
    code: 44,
  },
  {
    // id: 45,
    name: "Naâma",
    arName: "النعامة",
    code: 45,
  },
  {
    // id: 46,
    name: "Aïn Témouchent",
    arName: "عين تموشنت",
    code: 46,
  },
  {
    // id: 47,
    name: "Ghardaïa",
    arName: "غرداية",
    code: 47,
  },
  {
    // id: 48,
    name: "Relizane",
    arName: "غليزان",
    code: 48,
  },
  {
    // id: 49,
    name: "Timimoun",
    arName: "تيميمون",
    code: 49,
  },
  {
    // id: 50,
    name: "Bordj Baji Mokhtar",
    arName: "برج باجي مختار",
    code: 50,
  },
  {
    // id: 51,
    name: "Ouled Djellal",
    arName: "أولاد جلال",
    code: 51,
  },
  {
    // id: 52,
    name: "Béni Abbès",
    arName: "بني عباس",
    code: 52,
  },
  {
    // id: 53,
    name: "In Salah",
    arName: "عين صالح",
    code: 53,
  },
  {
    // id: 54,
    name: "In Guezzam",
    arName: "عين قزّام",
    code: 54,
  },
  {
    // id: 55,
    name: "Touggourt",
    arName: "تقرت",
    code: 55,
  },
  {
    // id: 56,
    name: "Djanet",
    arName: "جانت",
    code: 56,
  },
  {
    // id: 57,
    name: "El M'ghair",
    arName: "المغير",
    code: 57,
  },
  {
    // id: 58,
    name: "El Menia",
    arName: "المنيعة",
    code: 58,
  },
];

export const dummyProductData: Prisma.ProductUncheckedCreateInput[] = [
  {
    code: uniqueId(20),
    name: "Apple Watch Series 8 Gps + Cellular 45mm",
    description: "Couleur: Midnight",
    price: 5000,
    stock: 3,
    discount: 10,
    images: {
      create: {
        link: "https://scontent.falg6-2.fna.fbcdn.net/v/t45.5328-4/350058072_6619365291415410_3353060098354417131_n.jpg?stp=dst-jpg_p960x960&_nc_cat=107&ccb=1-7&_nc_sid=c48759&_nc_eui2=AeFaq8GFJOynTifnKQDYaH8sXI7Y4N6Fynxcjtjg3oXKfAJ8eqE31XSXmEQ_Lz-arJvfSJgKK0mi3aTZPyAu4jRN&_nc_ohc=BLd2ZpGo-C8AX_mcKUq&_nc_ht=scontent.falg6-2.fna&oh=00_AfADioqaDDdG_82yqV8DdccvyIcAI1gwG2ISiGlmcNLVYQ&oe=64875FA3",
      },
    },
  },
  // {
  //   code: uniqueId(20),
  //   name: "Samsung Galaxy Buds Plus, Bluetooth 5.0",
  //   description: "Couleur: Black",
  //   price: 12000,
  //   stock: 4,
  // },
];
