"use client";
import AuthProvider from "@/components/AuthProvider";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Commander - TRB Eshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`relative ${inter.className} bg-white dark:bg-[#040404]`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
