import "./globals.css";
import { type ReactNode } from "react";
import { Metadata } from "next";
import AppProviders from "@/components/AppProviders";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Commander - TRB Eshop",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`relative ${inter.className} h-screen max-h-screen  overflow-hidden bg-neutral-100 dark:bg-dark dark:[color-scheme:dark]`}
      >
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
